### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by outlaw-dame** [343max/komondor-mastodon#14]
There hasn’t been any updates nor can the betas be accessed

**Comment by 343max** [comment]
You can pick it up if you want to. 😀

I think by now there are a lot of very nice Mastodon clients out there so I don't have the motivation to build another one.

**Comment by outlaw-dame** [comment]
That’s understandable but just because there are a lot doesn’t mean yours would be any less. I wish I got to experience it and your vision. What are you working on currently?
